version: '2'
services:
  mongo:
    image: mvertes/alpine-mongo
    expose:
      - 27017
    command: "mongod --smallfiles --logpath=/dev/null"
  davis:
    build: .
    image: davis:production
    expose:
      - 3000
    links:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo/davis
      NODE_ENV: production
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./davis.nginx.conf:/etc/nginx/nginx.conf
    links:
      - davis
    ports:
      - "80:80"
      - "443:443"
